import { Inter } from "next/font/google";
import "./globals.css";

import styles from "./layout.module.css";
import Link from "next/link";
import Image from "next/image";
import img1 from "./Images/anpic3.jpeg";

import {
  FaBeer,
  FaCode,
  FaConnectdevelop,
  FaInstagram,
  FaNodeJs,
  FaReact,
} from "react-icons/fa";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className={styles.outer_div}>
          <div className={styles.sidebar}>
            <Image
              src={img1}
              className={styles.profile}
              alt="profile"
              priority={1}
            />

            <p className={styles.heading}>A Chaudhary </p>

            <div className={styles.link_box}>
              <Link className={styles.links} href="">
                <div className={styles.links_div}>
                  <FaConnectdevelop className={styles.icons} />
                  <p>Leetcode</p>
                </div>
              </Link>
              <Link className={styles.links} href="">
                <div className={styles.links_div}>
                  <FaCode className={styles.icons} />
                  <p>Flutter</p>
                </div>
              </Link>
              <Link className={styles.links} href="">
                <div className={styles.links_div}>
                  <FaNodeJs className={styles.icons} />
                  <p>Express</p>
                </div>
              </Link>
              <Link className={styles.links} href="">
                <div className={styles.links_div}>
                  <FaReact className={styles.icons} />
                  <p>Next js</p>
                </div>
              </Link>
              <Link className={styles.links} href="">
                <div className={styles.links_div}>
                  <FaReact className={styles.icons} />
                  <p>React js</p>
                </div>
              </Link>
              <div className={styles.contact_div}>
                <p>Having trouble?</p>
                <p>Contact us</p>
              </div>
            </div>
          </div>
          <div className={styles.right_div}>{children}</div>
        </div>
      </body>
    </html>
  );
}
